INSERT INTO USERS(USERNAME,PASSWORD, ENABLED) VALUES ( 'admin', '{bcrypt}$2a$10$et7t/56FULw.WohTI9fIpuu2G78xPUxhWGNAnrymZ6fchFRX0Nd1q', true);
INSERT INTO USERS(USERNAME,PASSWORD, ENABLED) VALUES ( 'gl', '{bcrypt}$2a$10$VT/n8x/VMzrBeoS6wW02g.a34ldNbb.HR2ZpS9oVff6lEyH33m9i6', true);


INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ( 'admin', 'ROLE_ADMIN');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ( 'gl', 'ROLE_USER');

INSERT INTO MENU_ITEM(NAME, PRICE) VALUES ( 'Panner Tikka Dry', 250 );
INSERT INTO MENU_ITEM(NAME, PRICE) VALUES ( 'Panner Tikka Curry', 300 );
INSERT INTO MENU_ITEM(NAME, PRICE) VALUES ( 'Panner Biryani', 350 );
INSERT INTO MENU_ITEM(NAME, PRICE) VALUES ( 'Peas Pulav', 275 );
INSERT INTO MENU_ITEM(NAME, PRICE) VALUES ( 'Naan', 100 );
INSERT INTO MENU_ITEM(NAME, PRICE) VALUES ( 'Lime Soda', 150 );
